use std::collections::HashMap;

use chrono::{DateTime, NaiveDate, NaiveTime, TimeZone, Utc};
use ham_plugin_sdk::{ProposalEnvelope, PROPOSAL_QSO_CREATE};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use uuid::Uuid;

use crate::{
    proposal::{submit_proposal, ProposalContext},
    store::LogbookEventStore,
    EventBus, QsoCurrentStateProjection,
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DuplicatePolicy {
    Skip,
    ImportAnyway,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdifImportOptions {
    pub duplicate_window_minutes: i64,
    pub duplicate_policy: DuplicatePolicy,
    pub station_callsign: String,
    pub operator_callsign: Option<String>,
    pub source_plugin_id: String,
    pub author_device_id: Uuid,
}

impl AdifImportOptions {
    pub fn mvp_default(
        station_callsign: impl Into<String>,
        source_plugin_id: impl Into<String>,
        author_device_id: Uuid,
    ) -> Self {
        Self {
            duplicate_window_minutes: 10,
            duplicate_policy: DuplicatePolicy::Skip,
            station_callsign: station_callsign.into(),
            operator_callsign: None,
            source_plugin_id: source_plugin_id.into(),
            author_device_id,
        }
    }
}

#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdifImportSummary {
    pub imported_count: usize,
    pub skipped_count: usize,
    pub duplicate_count: usize,
    pub rejected_count: usize,
    pub errors: Vec<String>,
}

pub type AdifRecord = HashMap<String, String>;

pub fn parse_adif(input: &str) -> Vec<AdifRecord> {
    let mut records = Vec::new();
    let mut current = AdifRecord::new();
    let bytes = input.as_bytes();
    let mut index = 0usize;

    while index < bytes.len() {
        if bytes[index] != b'<' {
            index += 1;
            continue;
        }
        let Some(end) = input[index..].find('>') else {
            break;
        };
        let tag = &input[index + 1..index + end];
        index += end + 1;
        let tag_lower = tag.to_ascii_lowercase();
        if tag_lower == "eoh" {
            continue;
        }
        if tag_lower == "eor" {
            if !current.is_empty() {
                records.push(current);
                current = AdifRecord::new();
            }
            continue;
        }
        let Some((field, length_part)) = tag.split_once(':') else {
            continue;
        };
        let length = length_part
            .split(':')
            .next()
            .and_then(|value| value.parse::<usize>().ok())
            .unwrap_or(0);
        if index + length > input.len() {
            break;
        }
        let value = input[index..index + length].to_owned();
        current.insert(field.to_ascii_uppercase(), value);
        index += length;
    }

    if !current.is_empty() {
        records.push(current);
    }

    records
}

pub fn export_adif(projection: &QsoCurrentStateProjection, include_deleted: bool) -> String {
    let mut output = String::from("Generated by KE8YGW Logger 0.1.0\n<ADIF_VER:5>3.1.4\n<EOH>\n");
    for record in projection.list(include_deleted) {
        append_field(
            &mut output,
            "CALL",
            record.payload.get("contacted_callsign"),
        );
        append_field(
            &mut output,
            "STATION_CALLSIGN",
            record.payload.get("station_callsign"),
        );
        append_field(
            &mut output,
            "OPERATOR",
            record.payload.get("operator_callsign"),
        );
        append_date_time(&mut output, &record.payload);
        append_field(&mut output, "BAND", record.payload.get("band"));
        append_frequency(&mut output, record.payload.get("frequency_hz"));
        append_field(&mut output, "MODE", record.payload.get("mode"));
        append_field(&mut output, "SUBMODE", record.payload.get("submode"));
        append_field(&mut output, "RST_SENT", record.payload.get("rst_sent"));
        append_field(&mut output, "RST_RCVD", record.payload.get("rst_received"));
        append_field(&mut output, "GRIDSQUARE", record.payload.get("grid"));
        append_field(&mut output, "NAME", record.payload.get("name"));
        append_field(&mut output, "QTH", record.payload.get("qth"));
        append_field(&mut output, "COMMENT", record.payload.get("notes"));
        append_field(&mut output, "MY_SIG", record.payload.get("my_sig"));
        append_field(
            &mut output,
            "MY_SIG_INFO",
            record.payload.get("my_sig_info"),
        );
        append_field(&mut output, "SIG", record.payload.get("contacted_sig"));
        append_field(
            &mut output,
            "SIG_INFO",
            record.payload.get("contacted_sig_info"),
        );
        output.push_str("<EOR>\n");
    }
    output
}

pub async fn import_adif<S, B>(
    store: &S,
    bus: &B,
    context: &ProposalContext,
    logbook_id: Uuid,
    input: &str,
    options: &AdifImportOptions,
) -> AdifImportSummary
where
    S: LogbookEventStore,
    B: EventBus,
{
    let mut summary = AdifImportSummary::default();
    let records = parse_adif(input);
    let mut projection = store
        .rebuild_projections(logbook_id)
        .await
        .unwrap_or_else(|_| QsoCurrentStateProjection::new());

    for record in records {
        let payload = match adif_record_to_qso_payload(&record, options) {
            Ok(payload) => payload,
            Err(error) => {
                summary.rejected_count += 1;
                summary.errors.push(error);
                continue;
            }
        };

        if options.duplicate_policy == DuplicatePolicy::Skip
            && is_duplicate(&projection, &payload, options.duplicate_window_minutes)
        {
            summary.duplicate_count += 1;
            summary.skipped_count += 1;
            continue;
        }

        let proposal = ProposalEnvelope::new(
            PROPOSAL_QSO_CREATE,
            logbook_id,
            None,
            None,
            options.author_device_id,
            options.source_plugin_id.clone(),
            1,
            payload,
        );

        match submit_proposal(store, bus, context, proposal).await {
            Ok(_) => {
                summary.imported_count += 1;
                projection = store
                    .rebuild_projections(logbook_id)
                    .await
                    .unwrap_or_else(|_| QsoCurrentStateProjection::new());
            }
            Err(error) => {
                summary.rejected_count += 1;
                summary.errors.push(error.to_string());
            }
        }
    }

    summary
}

fn adif_record_to_qso_payload(
    record: &AdifRecord,
    options: &AdifImportOptions,
) -> Result<Value, String> {
    let contacted_callsign = required(record, "CALL")?.to_ascii_uppercase();
    let mode = required(record, "MODE")?.to_ascii_uppercase();
    let started_at = adif_datetime(record, "QSO_DATE", "TIME_ON")?;
    let mut payload = json!({
        "station_callsign": record
            .get("STATION_CALLSIGN")
            .cloned()
            .unwrap_or_else(|| options.station_callsign.clone()),
        "operator_callsign": record
            .get("OPERATOR")
            .cloned()
            .or_else(|| options.operator_callsign.clone())
            .unwrap_or_else(|| options.station_callsign.clone()),
        "contacted_callsign": contacted_callsign,
        "started_at": started_at.to_rfc3339(),
        "mode": mode,
        "source": "imported/adif",
        "import_metadata": {
            "raw_adif": record
        }
    });

    copy(record, "BAND", &mut payload, "band");
    copy(record, "SUBMODE", &mut payload, "submode");
    copy(record, "RST_SENT", &mut payload, "rst_sent");
    copy(record, "RST_RCVD", &mut payload, "rst_received");
    copy(record, "GRIDSQUARE", &mut payload, "grid");
    copy(record, "NAME", &mut payload, "name");
    copy(record, "QTH", &mut payload, "qth");
    copy(record, "COMMENT", &mut payload, "notes");
    copy(record, "NOTES", &mut payload, "notes");
    copy(record, "MY_SIG", &mut payload, "my_sig");
    copy(record, "MY_SIG_INFO", &mut payload, "my_sig_info");
    copy(record, "SIG", &mut payload, "contacted_sig");
    copy(record, "SIG_INFO", &mut payload, "contacted_sig_info");

    if let Some(ended_at) = record
        .get("TIME_OFF")
        .and_then(|_| adif_datetime(record, "QSO_DATE", "TIME_OFF").ok())
    {
        payload["ended_at"] = json!(ended_at.to_rfc3339());
    }
    if let Some(freq) = record.get("FREQ").and_then(|freq| freq.parse::<f64>().ok()) {
        payload["frequency_hz"] = json!((freq * 1_000_000.0).round() as u64);
    }

    Ok(payload)
}

fn is_duplicate(
    projection: &QsoCurrentStateProjection,
    payload: &Value,
    window_minutes: i64,
) -> bool {
    let callsign = payload
        .get("contacted_callsign")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let mode = payload
        .get("mode")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let band = payload.get("band").and_then(Value::as_str);
    let Some(started_at) = payload
        .get("started_at")
        .and_then(Value::as_str)
        .and_then(|value| DateTime::parse_from_rfc3339(value).ok())
        .map(|value| value.with_timezone(&Utc))
    else {
        return false;
    };

    projection.list(false).into_iter().any(|record| {
        let existing = &record.payload;
        let existing_started = existing
            .get("started_at")
            .and_then(Value::as_str)
            .and_then(|value| DateTime::parse_from_rfc3339(value).ok())
            .map(|value| value.with_timezone(&Utc));
        let same_call = existing
            .get("contacted_callsign")
            .and_then(Value::as_str)
            .is_some_and(|value| value.eq_ignore_ascii_case(callsign));
        let same_mode = existing
            .get("mode")
            .and_then(Value::as_str)
            .is_some_and(|value| value.eq_ignore_ascii_case(mode));
        let same_band = match band {
            Some(band) => existing
                .get("band")
                .and_then(Value::as_str)
                .is_some_and(|value| value.eq_ignore_ascii_case(band)),
            None => true,
        };
        let close_time = existing_started.is_some_and(|existing_started| {
            (existing_started - started_at).num_minutes().abs() <= window_minutes
        });
        same_call && same_mode && same_band && close_time
    })
}

fn required(record: &AdifRecord, field: &str) -> Result<String, String> {
    record
        .get(field)
        .filter(|value| !value.trim().is_empty())
        .cloned()
        .ok_or_else(|| format!("ADIF record missing required field {field}"))
}

fn adif_datetime(
    record: &AdifRecord,
    date_field: &str,
    time_field: &str,
) -> Result<DateTime<Utc>, String> {
    let date = required(record, date_field)?;
    let time = record
        .get(time_field)
        .cloned()
        .unwrap_or_else(|| "000000".to_owned());
    let date = NaiveDate::parse_from_str(&date, "%Y%m%d")
        .map_err(|_| format!("invalid ADIF date {date}"))?;
    let padded_time = format!("{time:0<6}");
    let time = NaiveTime::parse_from_str(&padded_time[..6], "%H%M%S")
        .map_err(|_| format!("invalid ADIF time {padded_time}"))?;
    Ok(Utc.from_utc_datetime(&date.and_time(time)))
}

fn copy(record: &AdifRecord, adif: &str, payload: &mut Value, key: &str) {
    if let Some(value) = record.get(adif).filter(|value| !value.trim().is_empty()) {
        payload[key] = json!(value);
    }
}

fn append_field(output: &mut String, name: &str, value: Option<&Value>) {
    let Some(value) = value.and_then(Value::as_str) else {
        return;
    };
    if value.is_empty() {
        return;
    }
    output.push_str(&format!("<{name}:{}>{value}", value.len()));
}

fn append_frequency(output: &mut String, value: Option<&Value>) {
    let Some(hz) = value.and_then(Value::as_u64) else {
        return;
    };
    let mhz = hz as f64 / 1_000_000.0;
    let value = format!("{mhz:.6}");
    output.push_str(&format!("<FREQ:{}>{value}", value.len()));
}

fn append_date_time(output: &mut String, payload: &Value) {
    let Some(started_at) = payload
        .get("started_at")
        .and_then(Value::as_str)
        .and_then(|value| DateTime::parse_from_rfc3339(value).ok())
        .map(|value| value.with_timezone(&Utc))
    else {
        return;
    };
    let qso_date = started_at.format("%Y%m%d").to_string();
    let time_on = started_at.format("%H%M%S").to_string();
    output.push_str(&format!("<QSO_DATE:8>{qso_date}<TIME_ON:6>{time_on}"));

    if let Some(ended_at) = payload
        .get("ended_at")
        .and_then(Value::as_str)
        .and_then(|value| DateTime::parse_from_rfc3339(value).ok())
        .map(|value| value.with_timezone(&Utc))
    {
        let time_off = ended_at.format("%H%M%S").to_string();
        output.push_str(&format!("<TIME_OFF:6>{time_off}"));
    }
}

#[cfg(test)]
mod tests {
    use ham_plugin_sdk::{PluginCapability, PluginManifest};

    use crate::{InMemoryEventBus, InMemoryLogbookEventStore, OperatorRole};
    use crate::{LogbookEventStore, NewLogbookEvent};

    use super::*;

    #[test]
    fn parses_adif_fields() {
        let records = parse_adif("<CALL:5>K1ABC<MODE:3>SSB<EOR>");
        assert_eq!(records[0]["CALL"], "K1ABC");
        assert_eq!(records[0]["MODE"], "SSB");
    }

    #[tokio::test]
    async fn imports_adif_through_proposal_pipeline_and_exports() {
        let store = InMemoryLogbookEventStore::new();
        let bus = InMemoryEventBus::default();
        let logbook_id = Uuid::new_v4();
        let context = ProposalContext {
            plugin_manifest: PluginManifest {
                plugin_id: "importer".to_owned(),
                name: "Importer".to_owned(),
                version: "0.1.0".to_owned(),
                capabilities: vec![PluginCapability::QsoCreate],
            },
            operator_role: OperatorRole::Logger,
        };
        let options = AdifImportOptions::mvp_default("KE8YGW", "importer", Uuid::new_v4());
        let summary = import_adif(
            &store,
            &bus,
            &context,
            logbook_id,
            "<CALL:5>K1ABC<QSO_DATE:8>20260705<TIME_ON:6>120000<BAND:3>20m<MODE:3>SSB<EOR>",
            &options,
        )
        .await;

        assert_eq!(summary.imported_count, 1);
        let projection = store.rebuild_projections(logbook_id).await.unwrap();
        let exported = export_adif(&projection, false);
        assert!(exported.contains("<CALL:5>K1ABC"));
        assert!(exported.contains("<MODE:3>SSB"));
    }

    #[tokio::test]
    async fn duplicate_adif_records_are_skipped() {
        let store = InMemoryLogbookEventStore::new();
        let bus = InMemoryEventBus::default();
        let logbook_id = Uuid::new_v4();
        let context = ProposalContext {
            plugin_manifest: PluginManifest {
                plugin_id: "importer".to_owned(),
                name: "Importer".to_owned(),
                version: "0.1.0".to_owned(),
                capabilities: vec![PluginCapability::QsoCreate],
            },
            operator_role: OperatorRole::Logger,
        };
        let options = AdifImportOptions::mvp_default("KE8YGW", "importer", Uuid::new_v4());
        let adif = "<CALL:5>K1ABC<QSO_DATE:8>20260705<TIME_ON:6>120000<BAND:3>20m<MODE:3>SSB<EOR><CALL:5>K1ABC<QSO_DATE:8>20260705<TIME_ON:6>120500<BAND:3>20m<MODE:3>SSB<EOR>";
        let summary = import_adif(&store, &bus, &context, logbook_id, adif, &options).await;

        assert_eq!(summary.imported_count, 1);
        assert_eq!(summary.duplicate_count, 1);
    }

    #[tokio::test]
    async fn normal_adif_export_excludes_deleted_qsos() {
        let store = InMemoryLogbookEventStore::new();
        let logbook_id = Uuid::new_v4();
        let qso_id = Uuid::new_v4();
        let device_id = Uuid::new_v4();
        store
            .append_event(NewLogbookEvent {
                event_type: ham_plugin_sdk::OFFICIAL_LOG_QSO_CREATED.to_owned(),
                logbook_id,
                entity_id: Some(qso_id),
                author_operator_id: None,
                station_callsign: "KE8YGW".to_owned(),
                operator_callsign: Some("KE8YGW".to_owned()),
                author_device_id: device_id,
                source_device_id: device_id,
                correlation_id: Uuid::new_v4(),
                source_plugin_id: None,
                schema_version: 1,
                payload: json!({
                    "qso_id": qso_id,
                    "station_callsign": "KE8YGW",
                    "contacted_callsign": "K1ABC",
                    "started_at": "2026-07-05T12:00:00Z",
                    "mode": "SSB"
                }),
            })
            .await
            .unwrap();
        store
            .append_event(NewLogbookEvent {
                event_type: ham_plugin_sdk::OFFICIAL_LOG_QSO_DELETED.to_owned(),
                logbook_id,
                entity_id: Some(qso_id),
                author_operator_id: None,
                station_callsign: "KE8YGW".to_owned(),
                operator_callsign: Some("KE8YGW".to_owned()),
                author_device_id: device_id,
                source_device_id: device_id,
                correlation_id: Uuid::new_v4(),
                source_plugin_id: None,
                schema_version: 1,
                payload: json!({"reason": "test"}),
            })
            .await
            .unwrap();

        let projection = store.rebuild_projections(logbook_id).await.unwrap();
        assert!(!export_adif(&projection, false).contains("K1ABC"));
        assert!(export_adif(&projection, true).contains("K1ABC"));
    }
}
